apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: ms-service
  newName: wrpaiva2607/ms-service
  newTag: 13e0c8893e29421a5faf82ccd0232079d6789ea7
