apiVersion: v1
kind: Service
metadata:
    name: ms-service
spec:
    selector:
        app: ms-service
    ports:
        - protocol: TCP
          port: 8084
          targetPort: 8084
    type: LoadBalancer